# todo: health checks, env variables

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      db: 
        condition: service_started
      worker: 
        condition: service_started
      rabbitmq: 
        condition: service_healthy
      minio:
        condition: service_started
    command: python app.py

  worker:
    build: ./worker
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/seng468
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started

  db:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seng468
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.2.4-management-alpine
    #alpine is smaller but idk if it doesn't include any important stuff
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
  db_data:
