# todo: env variables in .env file

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/seng468
      - RABBITMQ_HOST=rabbitmq
      - MINIO_ENDPOINT=minio:9000
    cap_add:
      - SYS_PTRACE
    command: gunicorn --workers ${GUNICORN_WORKERS:-2} --bind 0.0.0.0:8080 app:app

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/seng468
      - RABBITMQ_HOST=rabbitmq
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - BUCKET_NAME=documents
    cap_add:
      - SYS_PTRACE
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  db:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seng468
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
  db_data:
